#!/usr/bin/env python3
"""amalgamate.py

Generates single_include/gauge15/sfv.hpp -- one self-contained header
containing the entire library -- from the real source under include/gauge15/.

This is generated, not hand-maintained, for the same reason nlohmann/json
and similar header-only libraries do this: hand-maintaining two copies of
the same code guarantees they eventually drift. include/gauge15/ is always
the source of truth; single_include/gauge15/sfv.hpp is a build artifact of
it, regenerated by this script and verified by actually compiling the
full test suite against it (see single_include/README.md).

How it works:
  1. Each header's dependency on other gauge15/ headers is known ahead of
     time (see FILES_IN_ORDER below -- computed once, by inspection,
     since the file set is small and stable; if a new header is added,
     add it here in the right position).
  2. FILES_IN_ORDER is already in dependency order: every file appears
     after everything it depends on.
  3. For each file: strip its own `#ifndef`/`#define`/`#endif` include-
     guard triple (the amalgamated output gets ONE guard, not one per
     original file) and strip every `#include "gauge15/...")` line (since
     the dependency is now satisfied by inlining, in order). External
     `#include <...>` lines are collected into a single deduplicated,
     first-seen-order block at the top instead of repeating per file.
  4. Concatenate the stripped bodies in dependency order, each preceded
     by a banner comment naming its original source file, wrap the whole
     thing in one header guard, and write it out.

Usage:
  python3 tools/amalgamate.py > single_include/gauge15/sfv.hpp
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
INCLUDE_DIR = REPO_ROOT / "include" / "gauge15"

# Dependency order matters: each file must appear after every file it
# depends on. Computed by inspection of each file's own #include "gauge15/..."
# lines -- sfv.hpp itself is the existing multi-file convenience
# aggregator and is intentionally NOT part of this list, since
# amalgamating IS what replaces it.
FILES_IN_ORDER = [
    "types.hpp",
    "result.hpp",
    "detail/utf8.hpp",
    "detail/base64.hpp",
    "parser.hpp",
    "serializer.hpp",
    "api.hpp",
]

IFNDEF_RE = re.compile(r"^#ifndef (SFV_\w+_HPP)\s*$")
DEFINE_RE = re.compile(r"^#define (SFV_\w+_HPP)\s*$")
ENDIF_RE = re.compile(r"^#endif\s*(//.*)?\s*$")
INTERNAL_INCLUDE_RE = re.compile(r'^#include "gauge15/[\w./]+\.hpp"(\s*//.*)?$')
EXTERNAL_INCLUDE_RE = re.compile(r'^#include <([\w./]+)>\s*$', re.M)


def strip_include_guard(text):
    """Removes exactly the #ifndef/#define lines (wherever they appear --
    NOT necessarily at the very start, since every file has its own doc-
    comment header first, which this function deliberately preserves: it
    becomes real, useful documentation inside the amalgamated file too,
    not just noise) and the final #endif line. Fails loudly if the
    expected guard triple isn't found, rather than silently emitting
    something subtly wrong.
    """
    lines = text.split("\n")
    ifndef_idx = next((i for i, l in enumerate(lines) if IFNDEF_RE.match(l)), None)
    assert ifndef_idx is not None, "no #ifndef SFV_..._HPP guard found"
    define_match = DEFINE_RE.match(lines[ifndef_idx + 1])
    assert define_match, "expected #define on the line right after #ifndef"
    assert IFNDEF_RE.match(lines[ifndef_idx]).group(1) == define_match.group(1), (
        "ifndef/define guard macro name mismatch"
    )

    endif_idx = next(
        (i for i in range(len(lines) - 1, -1, -1) if ENDIF_RE.match(lines[i])), None
    )
    assert endif_idx is not None, "no #endif found"
    assert endif_idx > ifndef_idx + 1, "#endif appears before the guarded body"

    before = lines[:ifndef_idx]
    body = lines[ifndef_idx + 2 : endif_idx]
    after = lines[endif_idx + 1 :]
    return "\n".join(before + body + after)


def process_file(relative_path):
    text = (INCLUDE_DIR / relative_path).read_text(encoding="utf-8")
    body = strip_include_guard(text)
    lines = [l for l in body.split("\n") if not INTERNAL_INCLUDE_RE.match(l)]
    return "\n".join(lines)


def main():
    external_includes = []  # first-seen order
    seen_externals = set()
    bodies = []

    for relative_path in FILES_IN_ORDER:
        text = (INCLUDE_DIR / relative_path).read_text(encoding="utf-8")
        for m in EXTERNAL_INCLUDE_RE.finditer(text):
            header = m.group(1)
            if header not in seen_externals:
                seen_externals.add(header)
                external_includes.append(header)

        body = process_file(relative_path)
        bodies.append((relative_path, body))

    out = []
    out.append("// sfv.hpp -- single-header amalgamation of gauge15.")
    out.append("//")
    out.append("// GENERATED FILE. DO NOT EDIT DIRECTLY.")
    out.append("//")
    out.append("// Source of truth is include/gauge15/*.hpp; this file is produced by")
    out.append("// tools/amalgamate.py, which concatenates every header in dependency")
    out.append("// order into one self-contained, drop-in file. Regenerate with:")
    out.append("//   python3 tools/amalgamate.py > single_include/gauge15/sfv.hpp")
    out.append("//")
    out.append("// A from-scratch, header-only C++20 implementation of RFC 9651,")
    out.append('// "Structured Field Values for HTTP". See the project README for')
    out.append("// scope, design notes, and usage examples -- this banner is")
    out.append("// intentionally short; the multi-file source under include/gauge15/ is")
    out.append("// where the real documentation (RFC section references, rationale for")
    out.append("// each design choice) lives, split up per concern rather than repeated")
    out.append("// here for every one of the ~10 files being concatenated.")
    out.append("")
    out.append("#ifndef SFV_SINGLE_INCLUDE_HPP")
    out.append("#define SFV_SINGLE_INCLUDE_HPP")
    out.append("")

    for header in external_includes:
        out.append(f"#include <{header}>")
    out.append("")

    for relative_path, body in bodies:
        out.append("// ============================================================")
        out.append(f"// {relative_path}")
        out.append("// ============================================================")
        out.append(body.strip("\n"))
        out.append("")

    out.append("#endif  // SFV_SINGLE_INCLUDE_HPP")
    out.append("")

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
